document: modularity-testing
version: 1
name: baseruntime
modulemd-url: http://pkgs.fedoraproject.org/cgit/modules/base-runtime.git/plain/base-runtime.yaml
service:
    port:
packages:
    rpms:
        - bash
        - coreutils
default_module: docker
module:
    docker:
        start:
        labels:
            description: "I dont know"
            io.k8s.description: "I dont know too"
        source: https://github.com/container-images/memcached.git
        container: docker=base-runtime-smoke
    rpm:
        start:
        stop:
        status:
        repos:
            - https://kojipkgs.stg.fedoraproject.org/repos/module-base-runtime-master-3/latest/x86_64/
test:
    processrunnig:
        - 'ls  / | grep bin'
